### ISSUE TITLE
sensitive file in repo

### ISSUE THREAD

**Issue by 0-GEE** [OhRai/Attendance-Tracker#1]
u might wanna remove [serviceAccountKey.json](https://github.com/OhRai/Attendance-Tracker/blob/main/serviceAccountKey.json) from the repo lol (use a .gitignore) also u might wanna regenerate those credentials afterwards so these leaked ones cant be used by any1

**Comment by OhRai** [comment]
Yup, forgot to do that when uploading it for the first time, it should be fixed now!
